import type { NextPage } from "next";
import Head from "next/head";
import SliderSection from "../components/home/SliderSection";
import BannerSection from "../components/home/BannerSection";
import FeaturesSection from "../components/home/FeaturesSection";
import ProductsSection from "../components/home/ProductsSection";
import SearchFullscreen from "../components/SearchFullscreen";
import CategorySection from "../components/home/CategorySection";
import { useEffect, useState } from "react";
import { Product } from "../interfaces";
import { getProducts } from "../services/ProductService";
import { getNewProducts } from "../utils/utils";

const Home: NextPage = () => {
  const [newProducts, setNewProducts] = useState<Product[]>([]);

  useEffect(() => {
    getProducts().then(response => {
      const products = getNewProducts(response)
      setNewProducts(products)
  })
  }, [])

  return (
    <div>
      <Head>
        <title>Click | Moda y Deporte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="section-slider height-v">
          <SliderSection />
        </section>

        <CategorySection />

        <ProductsSection {...newProducts} />

        <FeaturesSection />

        <SearchFullscreen />
      </main>
    </div>
  );
};

export default Home;
