import type { NextPage } from "next";
import Head from "next/head";
import SliderSection from "../components/home/SliderSection";
import BannerSection from "../components/home/BannerSection";
import FeaturesSection from "../components/home/FeaturesSection";
import ProductsSection from "../components/home/ProductsSection";
import SearchFullscreen from "../components/SearchFullscreen";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Click | Moda y Deporte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="section-slider height-v">
          <SliderSection />
        </section>

        <BannerSection />

        <ProductsSection />

        <FeaturesSection />

        <SearchFullscreen />
      </main>
    </div>
  );
};

export default Home;
