import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ProductsSection from "../components/home/ProductsSection";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Click | Indumentaria y Deporte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <!-- slider-area start --> */}
        <section className="slider-area pos-relative">
          <div className="slider-active slick-initialized slick-slider">
            <button
              type="button"
              className="slick-prev slick-arrow"
              style={{ display: "block" }}>
              {" "}
              <i className="fas fa-arrow-left"></i>{" "}
            </button>
            <div className="slick-list draggable">
              <div
                className="slick-track"
                style={{ opacity: 1, width: "5715px" }}>
                <div
                  className="single-slider slider-2 slide-1-style slide-height-2 d-flex align-items-center slick-slide slick-current slick-active"
                  data-background="img/slider/slide2-1.jpg"
                  data-slick-index="0"
                  style={{
                    backgroundImage: "url('img/slider/slide2-1.jpg')",
                    width: "1905px",
                    position: "relative",
                    left: "0px",
                    top: "0px",
                    zIndex: 999,
                    opacity: 1,
                  }}
                  aria-hidden="false"
                  tabIndex={0}>
                  <div className="shape-title bounce-animate">
                    <h2>2019</h2>
                  </div>
                  <div className="shape-icon bounce-animate">
                    <img
                      src="./Vue - Clean Minimal eCommerce HTML Template_files/shape-icon.png"
                      alt=""
                    />
                  </div>
                  <div className="container-fluid">
                    <div className="row">
                      <div className="col-xl-7">
                        <div className="slide-content pt-80">
                          <span
                            data-animation="fadeInRight"
                            data-delay=".2s"
                            className=""
                            style={{ animationDelay: "0.2s" }}>
                            Women Collection
                          </span>
                          <h1
                            data-animation="fadeInUp"
                            data-delay=".5s"
                            className=""
                            style={{ animationDelay: "0.5s" }}>
                            New Arrivals
                          </h1>
                          <div
                            className="slider-price mb-25"
                            data-animation="fadeInUp"
                            data-delay=".7s"
                            style={{ animationDelay: "0.7s" }}>
                            <span>$56.00</span>
                            <span className="old-price">$98.00</span>
                          </div>
                          <div className="slide-btn">
                            <a
                              className="btn theme-btn"
                              href="http://themepure.net/template/vue/vue/shop.html"
                              data-animation="fadeInLeft"
                              data-delay=".9s"
                              tabIndex={0}
                              style={{ animationDelay: "0.9s" }}>
                              shop now
                            </a>
                            <a
                              className="btn white-btn"
                              href="http://themepure.net/template/vue/vue/shop.html"
                              data-animation="fadeInRight"
                              data-delay="1.1s"
                              tabIndex={0}
                              style={{ animationDelay: "1.1s" }}>
                              category
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  className="single-slider slider-2 slide-1-style slide-height-2 d-flex align-items-center slick-slide"
                  data-background="img/slider/slide2-2.jpg"
                  data-slick-index="1"
                  style={{
                    backgroundImage: 'url("img/slider/slide2-2.jpg")',
                    width: "1905px",
                    position: "relative",
                    left: "-1905px",
                    top: "0px",
                    zIndex: "998",
                    opacity: "0",
                  }}
                  aria-hidden="true"
                  tabIndex={-1}>
                  <div className="shape-title bounce-animate">
                    <h2 className="home-2-shape">2019</h2>
                  </div>
                  <div className="shape-icon bounce-animate">
                    <img
                      src="./Vue - Clean Minimal eCommerce HTML Template_files/shape-icon.png"
                      alt=""
                    />
                  </div>
                  <div className="container-fluid">
                    <div className="row">
                      <div className="col-xl-7">
                        <div className="slide-content pt-80">
                          <span data-animation="fadeInRight" data-delay=".2s">
                            Women Collection
                          </span>
                          <h1 data-animation="fadeInUp" data-delay=".5s">
                            Women Product
                          </h1>
                          <div
                            className="slider-price mb-25"
                            data-animation="fadeInUp"
                            data-delay=".7s">
                            <span>$56.00</span>
                            <span className="old-price">$98.00</span>
                          </div>
                          <div className="slide-btn">
                            <a
                              className="btn theme-btn"
                              href="http://themepure.net/template/vue/vue/shop.html"
                              data-animation="fadeInLeft"
                              data-delay=".9s"
                              tabIndex={-1}>
                              shop now
                            </a>
                            <a
                              className="btn white-btn"
                              href="http://themepure.net/template/vue/vue/shop.html"
                              data-animation="fadeInRight"
                              data-delay="1.1s"
                              tabIndex={-1}>
                              category
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  className="single-slider slider-2 slide-1-style slide-height-2 d-flex align-items-center slick-slide"
                  data-background="img/slider/slide2-3.jpg"
                  data-slick-index="2"
                  style={{
                    backgroundImage: 'url("img/slider/slide2-3.jpg")',
                    width: "1905px",
                    position: "relative",
                    left: "-3810px",
                    top: "0px",
                    zIndex: "998",
                    opacity: "0",
                  }}
                  aria-hidden="true"
                  tabIndex={-1}>
                  <div className="shape-title bounce-animate">
                    <h2 className="home-2-shape">2019</h2>
                  </div>
                  <div className="shape-icon bounce-animate">
                    <img
                      src="./Vue - Clean Minimal eCommerce HTML Template_files/shape-icon.png"
                      alt=""
                    />
                  </div>
                  <div className="container-fluid">
                    <div className="row">
                      <div className="col-xl-7">
                        <div className="slide-content pt-80">
                          <span data-animation="fadeInRight" data-delay=".2s">
                            Women Collection
                          </span>
                          <h1 data-animation="fadeInUp" data-delay=".5s">
                            Trend Collection
                          </h1>
                          <div
                            className="slider-price mb-25"
                            data-animation="fadeInUp"
                            data-delay=".7s">
                            <span>$56.00</span>
                            <span className="old-price">$98.00</span>
                          </div>
                          <div className="slide-btn">
                            <a
                              className="btn theme-btn"
                              href="http://themepure.net/template/vue/vue/shop.html"
                              data-animation="fadeInLeft"
                              data-delay=".9s"
                              tabIndex={-1}>
                              shop now
                            </a>
                            <a
                              className="btn white-btn"
                              href="http://themepure.net/template/vue/vue/shop.html"
                              data-animation="fadeInRight"
                              data-delay="1.1s"
                              tabIndex={-1}>
                              category
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <button
              type="button"
              className="slick-next slick-arrow"
              style={{ display: "block" }}>
              {" "}
              <i className="fas fa-arrow-right"></i>
            </button>
          </div>
        </section>
        {/* <!-- slider-area end --> */}

        {/* <!-- banner area start --> */}
        <section className="banner-area pt-30 box-90">
          <div className="container-fluid">
            <div className="row">
              <div className="col-lg-6 col-md-12">
                <div className="banner-2 pos-relative mb-30">
                  <a href="http://themepure.net/template/vue/vue/shop.html">
                    <img
                      src="./Vue - Clean Minimal eCommerce HTML Template_files/banner1.jpg"
                      alt=""
                    />
                  </a>
                  <div className="banner-trend">
                    <span>Trendy Item</span>
                    <h2>
                      <a href="http://themepure.net/template/vue/vue/shop.html">
                        New Year Trend Coming 2019
                      </a>
                    </h2>
                    <div className="discover-link">
                      <a href="http://themepure.net/template/vue/vue/shop.html">
                        discover
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-lg-6 col-md-12">
                <div className="banner-2 pos-relative mb-30">
                  <a href="http://themepure.net/template/vue/vue/shop.html">
                    <img
                      src="./Vue - Clean Minimal eCommerce HTML Template_files/banner2.jpg"
                      alt=""
                    />
                  </a>
                  <div className="banner-look">
                    <span>Get the look</span>
                    <h2>Festive Looks</h2>
                    <img
                      src="./Vue - Clean Minimal eCommerce HTML Template_files/look.png"
                      alt=""
                    />
                    <p>Your delivery of outfit ideas, updated daily</p>
                    <a
                      href="http://themepure.net/template/vue/vue/shop.html"
                      className="btn theme-btn">
                      discover
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* <!-- banner area end --> */}

        <ProductsSection />

        {/* <!-- features-area start --> */}
        <section className="features-area box-90">
          <div className="container-fluid">
            <div className="theme-soft-bg fix pt-100 pb-50">
              <div className="row">
                <div className="col-xl-12">
                  <div className="area-title text-center mb-50">
                    <h2>Special Features</h2>
                    <p>Get special services from our shop.</p>
                  </div>
                </div>
              </div>
              <div className="features">
                <div className="single-seatures width-20 mb-50 text-center">
                  <i className="flaticon-shopping-cart-1"></i>
                  <span>Free Delivery</span>
                  <h3>Free Delivery</h3>
                </div>
                <div className="single-seatures width-20 mb-50 text-center">
                  <i className="flaticon-good"></i>
                  <span>100% Customer</span>
                  <h3>Feedbacks</h3>
                </div>
                <div className="single-seatures width-20 mb-50 text-center">
                  <i className="flaticon-return-1"></i>
                  <span>10 Days</span>
                  <h3>For Free Return</h3>
                </div>
                <div className="single-seatures width-20 mb-50 text-center">
                  <i className="flaticon-return"></i>
                  <span>Payment</span>
                  <h3>Secure System</h3>
                </div>
                <div className="single-seatures width-20 mb-50 text-center">
                  <i className="flaticon-customer-service"></i>
                  <span>24/7</span>
                  <h3>Online Supports</h3>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* <!-- features-area end --> */}

        {/* <!-- latest-blog-area start --> */}
        <section className="latest-blog-area pt-95 pb-60 box-90">
          <div className="container-fluid">
            <div className="row">
              <div className="col-xl-12">
                <div className="area-title text-center mb-50">
                  <h2>News Feeds</h2>
                  <p>Check it out every updates</p>
                </div>
              </div>
            </div>
            <div className="row">
              <div className="col-xl-4 col-lg-6 col-md-6">
                <div className="latest-news mb-40">
                  <div className="news__thumb mb-25">
                    <img
                      src="./Vue - Clean Minimal eCommerce HTML Template_files/lb4.jpg"
                      alt=""
                    />
                  </div>
                  <div className="news__caption white-bg">
                    <div className="news-meta mb-15">
                      <span>
                        <i className="far fa-calendar-check"></i> Sep 15, 2018{" "}
                      </span>
                      <span>
                        <a href="http://themepure.net/template/vue/vue/index-2.html#">
                          <i className="far fa-user"></i> Diboli
                        </a>
                      </span>
                      <span>
                        <a href="http://themepure.net/template/vue/vue/index-2.html#">
                          <i className="far fa-comments"></i> 23 Comments
                        </a>
                      </span>
                    </div>
                    <h2>
                      <a href="http://themepure.net/template/vue/vue/blog-details.html">
                        Inspiration Is Under Construction Business &amp; Fashion
                        2019. In this situation we do that..
                      </a>
                    </h2>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                      sed do eiusmod tempor incididunt ut labore et dolore magna
                      aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                      ullamco laboris nisi ut aliquip ex ea commodo..
                    </p>
                  </div>
                </div>
              </div>
              <div className="col-xl-4 col-lg-6 col-md-6">
                <div className="latest-news mb-40">
                  <div className="news__thumb mb-25">
                    <img
                      src="./Vue - Clean Minimal eCommerce HTML Template_files/lb5.jpg"
                      alt=""
                    />
                  </div>
                  <div className="news__caption white-bg">
                    <div className="news-meta mb-15">
                      <span>
                        <i className="far fa-calendar-check"></i> Sep 15, 2018{" "}
                      </span>
                      <span>
                        <a href="http://themepure.net/template/vue/vue/index-2.html#">
                          <i className="far fa-user"></i> Joly
                        </a>
                      </span>
                      <span>
                        <a href="http://themepure.net/template/vue/vue/index-2.html#">
                          <i className="far fa-comments"></i> 23 Comments
                        </a>
                      </span>
                    </div>
                    <h2>
                      <a href="http://themepure.net/template/vue/vue/blog-details.html">
                        Inspiration Is Under Construction Business &amp; Fashion
                        2019. In this situation we do that..
                      </a>
                    </h2>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                      sed do eiusmod tempor incididunt ut labore et dolore magna
                      aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                      ullamco laboris nisi ut aliquip ex ea commodo..
                    </p>
                  </div>
                </div>
              </div>
              <div className="col-xl-4 col-lg-6 col-md-6">
                <div className="latest-news mb-40">
                  <div className="news__thumb mb-25">
                    <img
                      src="./Vue - Clean Minimal eCommerce HTML Template_files/lb6.jpg"
                      alt=""
                    />
                  </div>
                  <div className="news__caption white-bg">
                    <div className="news-meta mb-15">
                      <span>
                        <i className="far fa-calendar-check"></i> Sep 15, 2018{" "}
                      </span>
                      <span>
                        <a href="http://themepure.net/template/vue/vue/index-2.html#">
                          <i className="far fa-user"></i> Joly
                        </a>
                      </span>
                      <span>
                        <a href="http://themepure.net/template/vue/vue/index-2.html#">
                          <i className="far fa-comments"></i> 23 Comments
                        </a>
                      </span>
                    </div>
                    <h2>
                      <a href="http://themepure.net/template/vue/vue/blog-details.html">
                        Inspiration Is Under Construction Business &amp; Fashion
                        2019. In this situation we do that..
                      </a>
                    </h2>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                      sed do eiusmod tempor incididunt ut labore et dolore magna
                      aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                      ullamco laboris nisi ut aliquip ex ea commodo..
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* <!-- latest-blog-area end --> */}

        {/* <!-- subscribe-area start --> */}
        <section className="subscribe-area box-105">
          <div className="subscribe-inner black-bg pt-70 pb-20">
            <div className="container-fluid">
              <div className="row">
                <div className="col-xl-5">
                  <div className="subscribe d-flex fix">
                    <div className="subscribe-icon">
                      <img
                        src="./Vue - Clean Minimal eCommerce HTML Template_files/subscribe.png"
                        alt=""
                      />
                    </div>
                    <div className="area-title white-color mb-50">
                      <h2>Newsletter</h2>
                      <p>Subsribe here for get every single updates</p>
                    </div>
                  </div>
                </div>
                <div className="col-xl-7">
                  <div className="subscribe fix">
                    <div className="subscribe-form mb-50">
                      <form action="http://themepure.net/template/vue/vue/index-2.html#">
                        <input
                          type="text"
                          placeholder="Enter your email address"
                        />
                        <button className="btn theme-btn" type="submit">
                          subscribe now
                        </button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* <!-- subscribe-area end --> */}

        {/* <!-- Fullscreen search --> */}
        <div className="search-wrap">
          <div className="search-inner">
            <i className="fas fa-times search-close" id="search-close"></i>
            <div className="search-cell">
              <form method="get">
                <div className="search-field-holder">
                  <input
                    type="search"
                    className="main-search-input"
                    placeholder="Search Entire Store..."
                  />
                </div>
              </form>
            </div>
          </div>
        </div>
        {/* <!-- end fullscreen search --> */}
        
      </main>
    </div>
  );
};

export default Home;
